In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import warnings 
warnings.filterwarnings('ignore')
import sklearn

In [6]:
print('numpy', np.__version__)
print('pandas', pd.__version__)
print('sklearn', sklearn.__version__)

numpy 2.1.3
pandas 2.2.3
sklearn 1.6.1


In [2]:
df = pd.read_csv('diabetes_012_health_indicators_BRFSS2015.csv')

In [3]:
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0


In [4]:
df = df.astype(int)

In [5]:
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
2     35346
1      4631
Name: count, dtype: int64

Since, the class 1 prediabetic & 2 Diabetec are same converting the class 1 & 2 to Diabetec as class 1

In [6]:
df['Diabetes_012'][df['Diabetes_012'] == 2] = 1
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
1     39977
Name: count, dtype: int64

In [7]:
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
1     39977
Name: count, dtype: int64

## As this is a diabetes indicator. I am considering the recall metric is best for this project

# Model Building

In [8]:
y = df['Diabetes_012']
X = df.drop('Diabetes_012', axis = 1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 73)

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((202944, 21), (50736, 21), (202944,), (50736,))

## Logistic Regression

In [11]:
logit = LogisticRegression()

In [12]:
logit.fit(X_train,y_train)

LogisticRegression()

In [13]:
logit_test = logit.predict(X_test)
logit_train = logit.predict(X_train)

In [14]:
print(accuracy_score(y_test,logit_test))
print(accuracy_score(y_train,logit_train))
print(confusion_matrix(y_test,logit_test))
print(classification_report(y_test,logit_test))

0.845060706401766
0.8456520025228634
[[41471  1270]
 [ 6591  1404]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     42741
           1       0.53      0.18      0.26      7995

    accuracy                           0.85     50736
   macro avg       0.69      0.57      0.59     50736
weighted avg       0.81      0.85      0.81     50736



## Naive Bayes

In [15]:
NB = GaussianNB(var_smoothing = 0.001)

In [16]:
NB.fit(X_train, y_train)

GaussianNB(var_smoothing=0.001)

In [17]:
NB_test = NB.predict(X_test)
NB_train = NB.predict(X_train)

In [18]:
print(accuracy_score(y_test,NB_test))
print(accuracy_score(y_train,NB_train))
print(confusion_matrix(y_test,NB_test))
print(classification_report(y_test,NB_test))

0.7969686218858404
0.7964709476505835
[[36767  5974]
 [ 4327  3668]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88     42741
           1       0.38      0.46      0.42      7995

    accuracy                           0.80     50736
   macro avg       0.64      0.66      0.65     50736
weighted avg       0.81      0.80      0.80     50736



## KNN 

In [19]:
knn = KNeighborsClassifier(n_neighbors = 3)

In [20]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [21]:
knn_test = knn.predict(X_test)
knn_train = knn.predict(X_train)

In [22]:
print(accuracy_score(y_test,knn_test))
print(accuracy_score(y_train,knn_train))
print(confusion_matrix(y_test,knn_test))
print(classification_report(y_test,knn_test))

0.8190042573320719
0.8920736754966887
[[39498  3243]
 [ 5940  2055]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.90     42741
           1       0.39      0.26      0.31      7995

    accuracy                           0.82     50736
   macro avg       0.63      0.59      0.60     50736
weighted avg       0.79      0.82      0.80     50736



## Decision Tree

In [15]:
Tree = DecisionTreeClassifier(class_weight = 'balanced')

In [16]:
Tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced')

In [17]:
tree_test = Tree.predict(X_test)
tree_train = Tree.predict(X_train)

In [18]:
print(accuracy_score(y_test,tree_test))
print(accuracy_score(y_train,tree_train))
print(confusion_matrix(y_test,tree_test))
print(classification_report(y_test,tree_test))

0.7782836644591612
0.9900662251655629
[[36921  5820]
 [ 5429  2566]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.87     42741
           1       0.31      0.32      0.31      7995

    accuracy                           0.78     50736
   macro avg       0.59      0.59      0.59     50736
weighted avg       0.78      0.78      0.78     50736



## Random Forest

In [27]:
Forest = RandomForestClassifier(n_estimators = 99, random_state = 73, n_jobs = -1, class_weight = 'balanced', oob_score = True, )

In [28]:
Forest.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=99, n_jobs=-1,
                       oob_score=True, random_state=73)

In [29]:
test_forest = Forest.predict(X_test)
train_forest = Forest.predict(X_train)

In [30]:
print(accuracy_score(y_test,test_forest))
print(accuracy_score(y_train,train_forest))
print(confusion_matrix(y_test,test_forest))
print(classification_report(y_test,test_forest))

0.8413749605802586
0.9921406890570797
[[41122  1619]
 [ 6429  1566]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91     42741
           1       0.49      0.20      0.28      7995

    accuracy                           0.84     50736
   macro avg       0.68      0.58      0.60     50736
weighted avg       0.81      0.84      0.81     50736



## SVM

In [ ]:
SVM has been taking a lot of time and giving bad results

In [19]:
svm = SVC(C=0.1, gamma = 0.01, kernel = 'rbf', class_weight='balanced')

In [ ]:
svm.fit(X_train, y_train)

In [ ]:
svm_test_preds = svm.predict(X_test)
svm_train_preds = svm.predict(X_train)

In [ ]:
print(accuracy_score(y_test,svm_test_preds))
print(accuracy_score(y_train,svm_train_preds))
print(confusion_matrix(y_test,svm_test_preds))
print(classification_report(y_test,svm_test_preds))

In [ ]:
svm2 = SVC(C=1, gamma = 0.001, kernel = 'rbf', class_weight='balanced')

In [ ]:
svm2.fit(X_train, y_train)

In [ ]:
svm2_test_preds = svm2.predict(X_test)
svm2_train_preds = svm2.predict(X_train)

In [ ]:
print(accuracy_score(y_test,svm2_test_preds))
print(accuracy_score(y_train,svm2_train_preds))
print(confusion_matrix(y_test,svm2_test_preds))
print(classification_report(y_test,svm2_test_preds))

In [ ]:
svm3 = SVC(C=1, gamma = 0.001, kernel = 'rbf', class_weight='balanced')

In [ ]:
svm3.fit(X_train, y_train)

In [ ]:
svm3_test_preds = svm3.predict(X_test)
svm3_train_preds = svm3.predict(X_train)

In [ ]:
print(accuracy_score(y_test,svm3_test_preds))
print(accuracy_score(y_train,svm3_train_preds))
print(confusion_matrix(y_test,svm3_test_preds))
print(classification_report(y_test,svm3_test_preds))