In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

import warnings
import pickle

In [3]:
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('diabetes_012_health_indicators_BRFSS2015.csv')

In [5]:
df.head()

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_012          253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [7]:
df = df.astype(int)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  int64
 1   HighBP                253680 non-null  int64
 2   HighChol              253680 non-null  int64
 3   CholCheck             253680 non-null  int64
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  int64
 6   Stroke                253680 non-null  int64
 7   HeartDiseaseorAttack  253680 non-null  int64
 8   PhysActivity          253680 non-null  int64
 9   Fruits                253680 non-null  int64
 10  Veggies               253680 non-null  int64
 11  HvyAlcoholConsump     253680 non-null  int64
 12  AnyHealthcare         253680 non-null  int64
 13  NoDocbcCost           253680 non-null  int64
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-n

In [9]:
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
2     35346
1      4631
Name: count, dtype: int64

In [10]:
df['Diabetes_012'][df['Diabetes_012'] == 2] = 1
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
1     39977
Name: count, dtype: int64

In [11]:
df['Diabetes_012'].value_counts()

Diabetes_012
0    213703
1     39977
Name: count, dtype: int64

In [12]:
df.columns

Index(['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [13]:
y = df['Diabetes_012']
X = df.drop('Diabetes_012', axis = 1)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 73)

In [15]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((202944, 21), (50736, 21), (202944,), (50736,))

In [16]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

In [17]:
rus = RandomUnderSampler(random_state = 42)

In [18]:
rus_X, rus_y = rus.fit_resample(X_train, y_train)

In [19]:
ros = RandomOverSampler(random_state = 42)

In [20]:
ros_X, ros_y = ros.fit_resample(X_train, y_train)

In [21]:
smote = SMOTE(random_state = 42)

In [22]:
smote_X, smote_y = smote.fit_resample(X_train, y_train)

## Logistic Regression

In [23]:
logit_rus = LogisticRegression()

In [24]:
logit_rus.fit(rus_X, rus_y)

LogisticRegression()

In [25]:
preds_rus_train = logit_rus.predict(X_train)
preds_rus_test = logit_rus.predict(X_test)

In [26]:
print(confusion_matrix(y_test, preds_rus_test))
print(classification_report(y_test, preds_rus_test))

[[30798 11943]
 [ 1922  6073]]
              precision    recall  f1-score   support

           0       0.94      0.72      0.82     42741
           1       0.34      0.76      0.47      7995

    accuracy                           0.73     50736
   macro avg       0.64      0.74      0.64     50736
weighted avg       0.85      0.73      0.76     50736



In [27]:
logit_ros = LogisticRegression()

In [28]:
logit_ros.fit(ros_X, ros_y)

LogisticRegression()

In [29]:
preds_ros_train = logit_ros.predict(X_train)
preds_ros_test = logit_ros.predict(X_test)

In [30]:
print(confusion_matrix(y_test, preds_ros_test))
print(classification_report(y_test, preds_ros_test))

[[31009 11732]
 [ 1964  6031]]
              precision    recall  f1-score   support

           0       0.94      0.73      0.82     42741
           1       0.34      0.75      0.47      7995

    accuracy                           0.73     50736
   macro avg       0.64      0.74      0.64     50736
weighted avg       0.85      0.73      0.76     50736



In [31]:
logit_smote = LogisticRegression()

In [32]:
logit_smote.fit(smote_X, smote_y )

LogisticRegression()

In [33]:
preds_smote_train = logit_smote.predict(X_train)
preds_smote_test = logit_smote.predict(X_test)

In [34]:
print(confusion_matrix(y_test,preds_smote_test))
print(classification_report(y_test, preds_smote_test))

[[31218 11523]
 [ 2621  5374]]
              precision    recall  f1-score   support

           0       0.92      0.73      0.82     42741
           1       0.32      0.67      0.43      7995

    accuracy                           0.72     50736
   macro avg       0.62      0.70      0.62     50736
weighted avg       0.83      0.72      0.75     50736



## Naive_Bayes

In [35]:
rus_NB = GaussianNB(var_smoothing = 0.001)
ros_NB = GaussianNB(var_smoothing = 0.001)
smote_NB = GaussianNB(var_smoothing = 0.001)

In [36]:
rus_NB.fit(rus_X, rus_y)

GaussianNB(var_smoothing=0.001)

In [37]:
ros_NB.fit(ros_X, ros_y)

GaussianNB(var_smoothing=0.001)

In [38]:
smote_NB.fit(smote_X, smote_y )

GaussianNB(var_smoothing=0.001)

In [39]:
rus_NB_test = rus_NB.predict(X_test)
rus_NB_train = rus_NB.predict(X_train)
ros_NB_test = ros_NB.predict(X_test)
ros_NB_train = ros_NB.predict(X_train)
smote_NB_test = smote_NB.predict(X_test)
smote_NB_train = smote_NB.predict(X_train)

In [40]:
print("Used Under sampler")
print(accuracy_score(y_test,rus_NB_test))
print(accuracy_score(y_train,rus_NB_train))
print(confusion_matrix(y_test,rus_NB_test))
print(classification_report(y_test,rus_NB_test))

Used Under sampler
0.7555187637969095
0.7528530037842952
[[33282  9459]
 [ 2945  5050]]
              precision    recall  f1-score   support

           0       0.92      0.78      0.84     42741
           1       0.35      0.63      0.45      7995

    accuracy                           0.76     50736
   macro avg       0.63      0.71      0.65     50736
weighted avg       0.83      0.76      0.78     50736



In [41]:
print('Used Over sampler')
print(accuracy_score(y_test,ros_NB_test))
print(accuracy_score(y_train,ros_NB_train))
print(confusion_matrix(y_test,ros_NB_test))
print(classification_report(y_test,ros_NB_test))

Used Over sampler
0.7564451277199622
0.7537300930305897
[[33337  9404]
 [ 2953  5042]]
              precision    recall  f1-score   support

           0       0.92      0.78      0.84     42741
           1       0.35      0.63      0.45      7995

    accuracy                           0.76     50736
   macro avg       0.63      0.71      0.65     50736
weighted avg       0.83      0.76      0.78     50736



In [42]:
print('Used Smote')
print(accuracy_score(y_test,smote_NB_test))
print(accuracy_score(y_train,smote_NB_train))
print(confusion_matrix(y_test,smote_NB_test))
print(classification_report(y_test,smote_NB_test))

Used Smote
0.7350204982655314
0.7347494875433617
[[32116 10625]
 [ 2819  5176]]
              precision    recall  f1-score   support

           0       0.92      0.75      0.83     42741
           1       0.33      0.65      0.44      7995

    accuracy                           0.74     50736
   macro avg       0.62      0.70      0.63     50736
weighted avg       0.83      0.74      0.77     50736



## KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rus_X_scaled = scaler.fit_transform(rus_X)
X_test_scaled = scaler.transform(X_test)

knn_rus = KNeighborsClassifier(n_neighbors=7)
knn_rus.fit(rus_X_scaled, rus_y)

preds_knn_rus_test = knn_rus.predict(X_test_scaled)
print('KNN : Using Under Sampler')
print(confusion_matrix(y_test, preds_knn_rus_test))
print(classification_report(y_test, preds_knn_rus_test))

KNN : Using Under Sampler
[[29363 13378]
 [ 2084  5911]]
              precision    recall  f1-score   support

           0       0.93      0.69      0.79     42741
           1       0.31      0.74      0.43      7995

    accuracy                           0.70     50736
   macro avg       0.62      0.71      0.61     50736
weighted avg       0.83      0.70      0.74     50736



In [44]:
ros_X_scaled = scaler.fit_transform(ros_X)
X_test_scaled = scaler.transform(X_test)

knn_ros = KNeighborsClassifier(n_neighbors=7)
knn_ros.fit(ros_X_scaled, ros_y)

preds_knn_ros_test = knn_ros.predict(X_test_scaled)
print('KNN : Using over sample')
print(confusion_matrix(y_test, preds_knn_ros_test))
print(classification_report(y_test, preds_knn_ros_test))

KNN : Using over sample
[[29765 12976]
 [ 2748  5247]]
              precision    recall  f1-score   support

           0       0.92      0.70      0.79     42741
           1       0.29      0.66      0.40      7995

    accuracy                           0.69     50736
   macro avg       0.60      0.68      0.60     50736
weighted avg       0.82      0.69      0.73     50736



In [45]:
smote_X_scaled = scaler.fit_transform(smote_X)
X_test_scaled = scaler.transform(X_test)

knn_smote = KNeighborsClassifier(n_neighbors=7)
knn_smote.fit(smote_X_scaled, smote_y)

preds_knn_smote_test = knn_smote.predict(X_test_scaled)
print('KNN : Using Smote')
print(confusion_matrix(y_test, preds_knn_smote_test))
print(classification_report(y_test, preds_knn_smote_test))

KNN : Using Smote
[[30115 12626]
 [ 3018  4977]]
              precision    recall  f1-score   support

           0       0.91      0.70      0.79     42741
           1       0.28      0.62      0.39      7995

    accuracy                           0.69     50736
   macro avg       0.60      0.66      0.59     50736
weighted avg       0.81      0.69      0.73     50736



## Decision Tree

In [46]:
from sklearn.tree import DecisionTreeClassifier
dt_rus = DecisionTreeClassifier(
    max_depth=5,
    min_samples_leaf=50,
    random_state=42
)

dt_rus.fit(rus_X, rus_y)

preds_dt_rus_test = dt_rus.predict(X_test)
print('DT : Using Under sample')
print(confusion_matrix(y_test, preds_dt_rus_test))
print(classification_report(y_test, preds_dt_rus_test))

DT : Using Under sample
[[29235 13506]
 [ 1775  6220]]
              precision    recall  f1-score   support

           0       0.94      0.68      0.79     42741
           1       0.32      0.78      0.45      7995

    accuracy                           0.70     50736
   macro avg       0.63      0.73      0.62     50736
weighted avg       0.84      0.70      0.74     50736



In [47]:
dt_ros = DecisionTreeClassifier(
    max_depth=5,
    min_samples_leaf=50,
    random_state=42
)

dt_ros.fit(ros_X, ros_y)

preds_dt_ros_test = dt_ros.predict(X_test)
print('DT : Using Over sampler')
print(confusion_matrix(y_test, preds_dt_ros_test))
print(classification_report(y_test, preds_dt_ros_test))

DT : Using Over sampler
[[29682 13059]
 [ 1839  6156]]
              precision    recall  f1-score   support

           0       0.94      0.69      0.80     42741
           1       0.32      0.77      0.45      7995

    accuracy                           0.71     50736
   macro avg       0.63      0.73      0.63     50736
weighted avg       0.84      0.71      0.74     50736



In [48]:
dt_smote = DecisionTreeClassifier(
    max_depth=5,
    min_samples_leaf=50,
    random_state=42
)

dt_smote.fit(smote_X, smote_y)

preds_dt_smote_test = dt_smote.predict(X_test)
print('DT : Using Smote')
print(confusion_matrix(y_test, preds_dt_smote_test))
print(classification_report(y_test, preds_dt_smote_test))

DT : Using Smote
[[26928 15813]
 [ 1636  6359]]
              precision    recall  f1-score   support

           0       0.94      0.63      0.76     42741
           1       0.29      0.80      0.42      7995

    accuracy                           0.66     50736
   macro avg       0.61      0.71      0.59     50736
weighted avg       0.84      0.66      0.70     50736



## Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier

rf_rus = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    min_samples_leaf=30,
    random_state=42,
    n_jobs=-1
)

rf_rus.fit(rus_X, rus_y)

preds_rf_rus_test = rf_rus.predict(X_test)
print('RF : Using under sampler')
print(confusion_matrix(y_test, preds_rf_rus_test))
print(classification_report(y_test, preds_rf_rus_test))

RF : Using under sampler
[[30093 12648]
 [ 1713  6282]]
              precision    recall  f1-score   support

           0       0.95      0.70      0.81     42741
           1       0.33      0.79      0.47      7995

    accuracy                           0.72     50736
   macro avg       0.64      0.74      0.64     50736
weighted avg       0.85      0.72      0.75     50736



In [51]:
rf_ros = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    min_samples_leaf=30,
    random_state=42,
    n_jobs=-1
)

rf_ros.fit(ros_X, ros_y)

preds_rf_ros_test = rf_ros.predict(X_test)
print('RF : Using Over sampler')
print(confusion_matrix(y_test, preds_rf_ros_test))
print(classification_report(y_test, preds_rf_ros_test))

RF : Using Over sampler
[[30426 12315]
 [ 1771  6224]]
              precision    recall  f1-score   support

           0       0.94      0.71      0.81     42741
           1       0.34      0.78      0.47      7995

    accuracy                           0.72     50736
   macro avg       0.64      0.75      0.64     50736
weighted avg       0.85      0.72      0.76     50736



In [52]:
rf_smote = RandomForestClassifier(
    n_estimators=300,
    max_depth=8,
    min_samples_leaf=30,
    random_state=42,
    n_jobs=-1
)

rf_smote.fit(smote_X, smote_y)

preds_rf_smote_test = rf_smote.predict(X_test)
print('RF : Using Smote')
print(confusion_matrix(y_test, preds_rf_smote_test))
print(classification_report(y_test, preds_rf_smote_test))

RF : Using Smote
[[29943 12798]
 [ 1912  6083]]
              precision    recall  f1-score   support

           0       0.94      0.70      0.80     42741
           1       0.32      0.76      0.45      7995

    accuracy                           0.71     50736
   macro avg       0.63      0.73      0.63     50736
weighted avg       0.84      0.71      0.75     50736



# Random Search CV

In [53]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer, recall_score, precision_score, f1_score
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler

In [54]:
pipeline = Pipeline([
    ('oversample', RandomOverSampler(random_state=42)),
    ('rf', RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ))
])

In [55]:
param_dist = {
    'rf__n_estimators': [200, 300, 400, 500],
    'rf__max_depth': [6, 8, 10, None],
    'rf__min_samples_split': [20, 40, 60],
    'rf__min_samples_leaf': [10, 20, 30],
    'rf__max_features': ['sqrt', 'log2']
}

In [56]:
scoring = {
    'recall': make_scorer(recall_score, pos_label=1),
    'precision': make_scorer(precision_score, pos_label=1),
    'f1_macro': make_scorer(f1_score, average='macro')
}

In [ ]:
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=30,
    scoring=scoring,
    refit='recall',  
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)
random_search.fit(ros_X, ros_y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


In [ ]:
best_model = random_search.best_estimator_

y_pred = best_model.predict(X_test)

print("Best Params:\n", random_search.best_params_)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Best Params:
 {'rf__n_estimators': 200, 'rf__min_samples_split': 60, 'rf__min_samples_leaf': 10, 'rf__max_features': 'log2', 'rf__max_depth': 8}

Confusion Matrix:
[[30366 12375]
 [ 1763  6232]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.71      0.81     42741
           1       0.33      0.78      0.47      7995

    accuracy                           0.72     50736
   macro avg       0.64      0.74      0.64     50736
weighted avg       0.85      0.72      0.76     50736



In [ ]:
print("Best CV Recall:", random_search.cv_results_['mean_test_recall'][random_search.best_index_])
print("Best CV Precision:", random_search.cv_results_['mean_test_precision'][random_search.best_index_])
print("Best CV Macro F1:", random_search.cv_results_['mean_test_f1_macro'][random_search.best_index_])

Best CV Recall: 0.7786565788782911
Best CV Precision: 0.3318309388541657
Best CV Macro F1: 0.6369219110602238


In [ ]:
# End of RandomSearchCv

In [ ]:
with open('diab_model.pkl', 'wb') as file:
    pickle.dump(best_model, file)